version: '3'
services:
  deesylab:
    build:
      context: .
    image: deesylab-cache
    restart: always
    networks:
      - layko_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:deesylab.cchampou.me"
      - "traefik.backend.port=80"

networks:
  layko_net:
    driver: bridge