version: '3'
services:
  deesylab:
    build:
      context: .
    image: deesylab-cache
    restart: always
    networks:
      - layko_net
    ports:
    - 8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:deesylab.cchampou.me"
      - "traefik.backend.port=80"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"


networks:
  layko_net:
    driver: bridge