version: '3'
services:
  deesylab:
    build:
      context: .
    image: deesylab-cache
    restart: always
    ports:
    - 8000:80
    volumes:
      - ./cache:/var/cache/nginx/
    labels:
      - "traefik.frontend.rule=Host:deesylab.cchampou.me"
      - "traefik.backend.port=80"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"

networks:
  default:
    external:
      name: layko_layko_net